### GET All Pruducts Request on Products Route
GET http://localhost:3000/Products

### PUT a Product on Products Route
POST http://localhost:3000/Products
Content-Type: application/json

{
    "Name": "Περιστερ1 2",
    "Description": "test 2 mmmmmmmmmm 555555",
    "Price": 100000,
    "Sale": true,
    "Photo": "https://i.pinimg.com/736x/4f/d3/d7/4fd3d766838da8d46930d4855a224535--gdansk-poland-crazy-houses.jpg",
    "ZipCode": 11111,
    "Region": "Athens",
    "Roof": 3,
    "Area": 110,
    "Bedrooms": 3
}


### PUT a Product on Products Route
POST http://localhost:3000/Products
Content-Type: application/x-www-form-urlencoded

name=kati2&price=2000

###
GET http://localhost:3000/Products/6344342cb584adcb80eb47fa


###
PATCH http://localhost:3000/Products/6344342cb584adcb80eb47fa
Content-Type: application/json

{
    
    "Area": 21
    
}


###
DELETE http://localhost:3000/Products/633ec1288edb18092c09619a


###Error
GET http://localhost:3000/xz


###
GET http://localhost:3000/test?name=imac&price=1000